apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:

  MYSQL_ROOT_PASSWORD: "root_password"
  DB_PASSWORD: "root_password"  
  MONGO_INITDB_ROOT_PASSWORD: "password123"
  
  OPENSKY_PASSWORD: "VEbMwkVFoYC9L9E6lZCHRdZSXVyp5XKP"
  SENDER_PASSWORD: "ggia fxdd lyon utkw"

  SENDER_PASSWORD: "eguw bxlq qijg ybnn"

  MONGO_URI: "mongodb://admin:password123@data-db:27017"